movie-imdb-dj/movie/urls.py
from django.urls import path 
from . import views 


app_name = 'movie'

urlpatterns = [
   
    path('' , views.MovieList.as_view() , name='movie_list'),
    path("category/<str:category>/", views.MovieCategory.as_view(), name="movie_category"),
    path("language/<str:language>/", views.MovieLanguage.as_view(), name="movie_language"),
    path("search/", views.MovieSearch.as_view(), name="movie_search"),
    path("year/<int:year>/", views.MovieYear.as_view(), name="movie_year"),
    path('<slug:slug>/'  , views.MovieDetail.as_view() , name='movie_detail'),
]

movie-imdb-dj/project/urls.py
from os import name
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from movie.views import HomeView

urlpatterns = [
    path('' , HomeView.as_view() , name='home'),
    path('admin/', admin.site.urls),
    path('movie/' , include('movie.urls' , namespace='movie')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie-imdb-dj/movie/models.py
from django.db import models

# Create your models here.
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from multiselectfield import MultiSelectField
from django.utils.text import slugify

CATEGORY_CHOICES = ( 
    ('action'  , 'ACTION'),
    ('drama' , 'DRAMA'),
    ('romance', 'ROMANCE'),
    ('comedy' , 'COMEDY')
)

LANGUNAGE_CHOICES = (
    ('english' , 'ENGLISH'),
    ('korean' , 'KOREAN'),
  
)

STATUS_CHOICES = (
    ('RA' , 'recently added'),
    ('MW' , 'most watched'),
    ('TR' , 'top rated')
)

class Movie(models.Model):

    title = models.CharField(_("title"), max_length=50)
    description  = models.TextField(_("description"))
    image = models.ImageField(_("image"), upload_to='movie', blank=True , null=True)
    banner = models.ImageField(_("banner"), upload_to='movie_banner',  blank=True , null=True)
    category = models.CharField(_("category"), choices=CATEGORY_CHOICES,  max_length=50)
    language = models.CharField(_("language"), choices=LANGUNAGE_CHOICES , max_length=30)
    status = models.CharField(_("status"), choices=STATUS_CHOICES  , max_length=30)
    year_of_production  = models.DateTimeField(_("year of production"),auto_now_add=False)
    cast = models.CharField(_("cast"), max_length=50)
    views_count = models.IntegerField(_("views count ") , default=0)
    slug = models.SlugField(_("slug") , null=True , blank=True)
    trailer = models.URLField(_("movie trailer"), max_length=200)
 

    class Meta:
        verbose_name = _("Movie")
        verbose_name_plural = _("Movies")

    def __str__(self):
        return self.title

    def save(self , *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Movie , self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("movie:MovieDetail", kwargs={"pk": self.pk})





class WatchedLink(models.Model):
    movie = models.ForeignKey(Movie, verbose_name=_("movie"), on_delete=models.CASCADE)
    links = models.URLField(_("links"), max_length=200)

    class Meta:
        verbose_name = _("WatchedLink")
        verbose_name_plural = _("WatchedLinks")

    def __str__(self):
        return str(self.movie.title)



class DownloadLink(models.Model):
    movie = models.ForeignKey(Movie, verbose_name=_("movie"), on_delete=models.CASCADE)
    links = models.URLField(_("links"), max_length=200)

    class Meta:
        verbose_name = _("DownloadLink")
        verbose_name_plural = _("DownloadLinks")

    def __str__(self):
        return str(self.movie.title)

movie-imdb-dj/movie/forms.py
from django import forms 
from .models import Comment



class CommentForm(forms.ModelForm):
    """Form definition for Comment."""

    class Meta:
        """Meta definition for Commentform."""

        model = Comment
        fields = ('name' , 'content',)

movie-imdb-dj/movie/views.py
from typing import List
from django.db.models.query import QuerySet
from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView , DetailView

import movie
from .models import Movie  , DownloadLink , WatchedLink
from django.views.generic.dates import YearArchiveView



class MovieList(ListView):
    model = Movie
    paginate_by  = 2
   



class HomeView(ListView):
    model = Movie
    template_name = 'movie/home.html'


    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context["top_rated"] = Movie.objects.filter(status='TR')
        context['most_watched']  = Movie.objects.filter(status='MW')
        context['recently_added'] = Movie.objects.filter(status='RA')
        return context
    










class MovieDetail(DetailView):
    model = Movie

    # todo get one movie 

    def get_object(self):
        object = super(MovieDetail , self).get_object()
        object.views_count += 1
        object.save()
        return object

    # todo retrive link of this movie 

    def get_context_data(self, **kwargs):
        context = super(MovieDetail ,self).get_context_data(**kwargs)
        context["links"] = WatchedLink.objects.filter(movie=self.get_object())
        context['related_movies'] = Movie.objects.filter(category=self.get_object().category)#.order_by['created'][0:6]
        return context

    def get_context_data(self, **kwargs):
        context = super(MovieDetail ,self).get_context_data(**kwargs)
        context["links"] = DownloadLink.objects.filter(movie=self.get_object())
        context['related_movies'] = Movie.objects.filter(category=self.get_object().category)#.order_by['created'][0:6]
        return context
    

class MovieCategory(ListView):
    model = Movie
    paginate_by  = 2
  

    # todo get category for one movie 
    def get_queryset(self):
        self.category = self.kwargs['category']
        movies = Movie.objects.filter(category=self.category)
        return movies


    def get_context_data(self, **kwargs):
        context = super(MovieCategory , self).get_context_data(**kwargs)
        context["movie_category"] = self.category
        return context
    


class MovieLanguage(ListView):
    model = Movie
    paginate_by = 2


    def get_queryset(self):
        self.language = self.kwargs['language']
        return Movie.objects.filter(language=self.language)


    def get_context_data(self, **kwargs):
        context = super(MovieLanguage , self).get_context_data(**kwargs)
        context["movie_language"] = self.language
        return context
    
    
    
    
class MovieSearch(ListView):
    model = Movie
    paginate_by = 1


    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = self.model.objects.filter(title__icontains=query)
            print(query)
            print(object_list)
        else:
            object_list = self.model.objects.none()

        return object_list
    



class MovieYear(YearArchiveView):
    queryset = Movie.objects.all()
    date_field = 'year_of_production'
    make_object_list = True
    allow_future = True

    print(queryset)

movie-imdb-dj/templates/base.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Most Watched</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">

	<script src="js/jquery-3.1.1.min.js"></script>
	<script src="js/script.js"></script>


	<!-- Demo styles -->
	<style>



	</style>
</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"><a href="index.html"><img src="{% static 'img/logo.svg' %}" alt="Logo"></figure></a>
			<nav class="menu">
				<ul>
					<li><a href="{% url 'movie:movie_list' %}">Home</a></li>
					<li><a>Genres</a>
						<ul>
							<li><a href="{% url 'movie:movie_category' 'action' %}">Action</a></li>
							<li><a href="{% url 'movie:movie_category' 'comedy' %}">Comedy</a></li>
							<li><a href="{% url 'movie:movie_category' 'drama' %}">Drama</a></li>
							<li><a href="{% url 'movie:movie_category' 'romance'  %}">Romance</a></li>
						</ul>
					</li>
					<li><a>Year</a>
						<ul>
							
					
								
							<li><a href="{% url 'movie:movie_year' year=2020 %}">2020</a></li>
							<li><a href="{% url 'movie:movie_year' year=2021 %}">2021</a></li>
							
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="{%url 'movie:movie_category' 'english' %}">English</a></li>
							<li><a href="{%url 'movie:movie_category' 'korean' %}">Korean</a></li>
						</ul>
					</li>
					<li><a href="mostwatched.html">Most Watched</a></li>
					<li class="mobsearch">
						<form class="mobform">
							<input type="text" name="s" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search" method="GET" action="{% url 'movie:movie_search' %}">
				{% csrf_token %}
				<input type="text" name="query" value="{{ request.GET.q}}" class="searchfield" placeholder="Search...">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="{% static 'img/menu.svg' %}"></div>
		</header>


		
		{% block body %}
			
		{% endblock body %}


		
		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="contact.html">Contact</a></li>
					<li><a href="terms.html">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

		
	</div>

	<!-- Swiper JS -->
	<script src="{% static 'js/swiper.min.js'%}"></script>

	<!-- Initialize Swiper -->
	<script>
		$(document).ready(function(){


			var swiper = new Swiper('.homeslider > .swiper-container', {
				pagination: '.swiper-pagination',
				paginationClickable: true,
				preventClicks:false,
				preventClicksPropagation:false,
				effect:'fade',
				breakpoints: {
					320: {
						height:200
					},

					480: {
						height:300
					},

					768: {
						height:400
					},
					1024: {
						height:500
					}
				}
			});

			var recentswiper = new Swiper('.recentslider > .swiper-container', {
				nextButton: '.recent-next',
				prevButton: '.recent-prev',
				slidesPerView: 8,
				paginationClickable: true,
				preventClicks:false,
				preventClicksPropagation:false,
				spaceBetween: 10,
				breakpoints: {
					320: {
						slidesPerView: 3,
						spaceBetween: 5
					},

					480: {
						slidesPerView: 3,
						spaceBetween: 5
					},

					768: {
						slidesPerView: 5,
						spaceBetween: 5
					},
					1024: {
						slidesPerView: 6,
						spaceBetween: 10
					}
				}
			});

			var mostswiper = new Swiper('.mostslider > .swiper-container', {
				nextButton: '.most-next',
				prevButton: '.most-prev',
				slidesPerView: 8,
				paginationClickable: true,
				preventClicks:false,
				preventClicksPropagation:false,
				spaceBetween: 10,
				breakpoints: {
					320: {
						slidesPerView: 3,
						spaceBetween: 5
					},

					480: {
						slidesPerView: 3,
						spaceBetween: 5
					},

					768: {
						slidesPerView: 5,
						spaceBetween: 5
					},
					1024: {
						slidesPerView: 6,
						spaceBetween: 10
					}
				}
			});

			var topswiper = new Swiper('.topslider > .swiper-container', {
				nextButton: '.top-next',
				prevButton: '.top-prev',
				slidesPerView: 8,
				paginationClickable: true,
				preventClicks:false,
				preventClicksPropagation:false,
				spaceBetween: 10,
				breakpoints: {
					320: {
						slidesPerView: 3,
						spaceBetween: 5
					},

					480: {
						slidesPerView: 3,
						spaceBetween: 5
					},

					768: {
						slidesPerView: 5,
						spaceBetween: 5
					},
					1024: {
						slidesPerView: 6,
						spaceBetween: 10
					}
				}
			});

		});

		
	</script>


</div>
</body>
</html>

movie-imdb-dj/templates/movie/home.html
{% extends 'base.html' %}
{% load static  %}

{% block body %}


		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster1.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 2</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 3</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>

		<main class="content">
			<section class="panel">
				<h2>Recently Added</h2>
				<div class="recentslider">
					<div class="swiper-container">
						<div class="swiper-wrapper">
							
							{% for movie  in recently_added %}
							
								
							<div class="swiper-slide"><a href="single.html"><img src="{{ movie.image.url }}"><h3 class="hometitle">{{ movie.title }}</h3></a></div>
							
							{% endfor %}

							<div class="swiper-slide"><a href="mostwatched.html"><img src="{% static 'img/others.png' %}"></a></div>
						</div>
						<div class="nextdirection recent-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
						<div class="leftdirection recent-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
					</div>
				</div>
			</section>

			<section class="panel">
				<h2>Most Watched</h2>
				<div class="mostslider">
					<div class="swiper-container">
						<div class="swiper-wrapper">
							
							{% for movie in most_watched  %}
								

								
							<div class="swiper-slide"><a href="single.html"><img src="{{ movie.image.url}}"><h3 class="hometitle">{{ movie.title}}</h3></a></div>
							{% endfor %}

							<div class="swiper-slide"><a href="mostwatched.html"><img src="{% static 'img/others.png' %}"></a></div>
						</div>
						<div class="nextdirection recent-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
						<div class="leftdirection recent-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
						<!-- Add Pagination -->
					</div>
				</div>
			</section>

			<section class="panel">
				<h2>Top Rated</h2>
				<div class="topslider">
					<div class="swiper-container">
						<div class="swiper-wrapper">
							
							{% for movie in top_rated  %}
				
							<div class="swiper-slide"><a href="single.html"><img src="{{ movie.image.url}}"><h3 class="hometitle">{{ movie.title }}</h3></a></div>
							{% endfor %}

							<div class="swiper-slide"><a href="mostwatched.html"><img src="{% static 'img/others.png' %}"></a></div>
						</div>
						<div class="nextdirection recent-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
						<div class="leftdirection recent-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
						<!-- Add Pagination -->
					</div>
				</div>
			</section>

			
		</main>

	
{% endblock body %}
	

movie-imdb-dj/templates/movie/movie_archive_year.html
		{% extends 'base.html' %}
         
        {% load static  %}
        
        {% block body %}

        <div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster1.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 2</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 3</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>

        <main class="content">
			<section class="centered">
           
			 
			 {% if movie_category %}

			 <h3>{{ movie_category|title }} Movies </h3>
				 
			 {% endif %}

			 {% if movie_language %}

			 <h3>{{ movie_language|title }}  </h3>
				 
			 {% endif %}


				 
				<div class="movies">
                    
                    {% for movie in object_list  %}

                    <div class="mov">
						<a href="{{get_absolute_url }}">
							<img src="{{ movie.image.url }}">
							<h2 class="movietitle">{{ movie.title }}</h2>
						</a>
					</div>
                    {% empty %}
					<h3>There are no Movies in the Category</h3>
                    {% endfor %}
                        
					
				
				</div>
                
                {% if is_paginated  %}

                
				<nav class="pagination">
					<ul>
                        
                        {% if page_obj.has_previous  %}
                        <li><a href="?page={{page_obj.previous_page_number }}">Prev</a></li>
                        {% else %}
                        <li class="disabled"></li>
                        {% endif %}
                            
						
					     
                         {% for pages  in  page_obj.paginator.page_range %}
                         
                         {% if page_obj.number == pages  %}
                         <li><a href="#">{{ pages }} </a></li>
                         {% else %}
                         <li><a href="?page={{pages}}">{{ pages }} </a></li>
                         {% endif %}
                             
                       
                             
                         {% endfor %}
                             
						


                        {% if page_obj.has_next   %}
                        <li><a href="?page={{page_obj.next_page_number }}">Next</a></li>
                            
                        {% else %}
                        <li class="disabled"></li>
                        {% endif %}
					</ul>
				</nav>
                    
                {% endif %}
                    

			</section>

		</main>

            
        {% endblock body %}
            
	

movie-imdb-dj/templates/movie/movie_detail.html
{% extends 'base.html' %}
         
{% load static  %}

{% block body %}


		<main class="content">
			<div class="single">

                <section class="trailer">
					<h3>Trailer</h3>
					<div class="trailer_frame">
						<iframe width="560" height="315" src="{{ object.trailer }}" frameborder="0" allowfullscreen></iframe>
					</div>
				</section>

				<section class="movie">
					<img src="{{ object.image.url }}">
					<ul>
						<li>{{ object }}</li>
						<li>{{ object.description }}</li>
						<li><a href="#">{{ object.category }} </a></li>
						<li><a href="#">{{ object.cast }}</a></li>
						<li>{{ object.views_count}} Views</li>
					</ul>
				</section>
				<section class="links">
					<h3>Links</h3>
					<ul class="dlinks">
						<li><a>Download</a></li>
						
						{% for link in links  %}
						
						

						<li><a href="{{ link.link }} ">Link{{ forloop.counter }}</a></li>
					
					
						{% endfor %}
							
					
						
					</ul>
					<ul class="wlinks">
						<li><a>Watch</a></li>
							
						{% for link in links  %}
						
					

						<li><a href="{{ link.link }} ">Link{{ forloop.counter }}</a></li>
							
					
					
						{% endfor %}
							
					</ul>
				</section>

				<section class="related">
					<h3>Related movies</h3>
					
					{% for movie in related_movies  %}

						
					<div class="relatemovie">
						<a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{ movie.image.url }}"></a>
						<a href="{% url 'movie:movie_detail' movie.slug %}"><span class="relatedname">{{ movie.title }}</span></a>
					</div>
			
						
					{% endfor %}
					

				</section>

				<section class="comments">
					<h3>Comments</h3>
				</section>
			</div>
		</main>


        {% endblock body %}
            

movie-imdb-dj/templates/movie/movie_list.html
		{% extends 'base.html' %}
         
        {% load static  %}
        
        {% block body %}

        <div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					
					{% for movie in  object_list %}

					<div class="swiper-slide">
						<img src="{{movie.image.url}}">
						<div class="caption">
							<div class="captioninside">
								<h3>{{ movie.title}}</h3>
								<p>{{ movie.description }}</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				
						
					{% endfor %}
						
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>

        <main class="content">
			<section class="centered">
           
			 
			 {% if movie_category %}

			 <h3>{{ movie_category|title }} Movies </h3>
				 
			 {% endif %}

			 {% if movie_language %}

			 <h3>{{ movie_language|title }}  </h3>
				 
			 {% endif %}


				 
				<div class="movies">
                    
                    {% for movie in object_list  %}

                    <div class="mov">
						<a href="{% url 'movie:movie_detail' movie.slug %}">
							<img src="{{ movie.image.url }}">
							<h2 class="movietitle">{{ movie.title }}</h2>
						</a>
					</div>
                    {% empty %}
					<h3>There are no Movies in the Category</h3>
                    {% endfor %}
                        
					
				
				</div>
                
                {% if is_paginated  %}

                
				<nav class="pagination">
					<ul>
                        
                        {% if page_obj.has_previous  %}
                        <li><a href="?page={{page_obj.previous_page_number }}">Prev</a></li>
                        {% else %}
                        <li class="disabled"></li>
                        {% endif %}
                            
						
					     
                         {% for pages  in  page_obj.paginator.page_range %}
                         
                         {% if page_obj.number == pages  %}
                         <li><a href="#">{{ pages }} </a></li>
                         {% else %}
                         <li><a href="?page={{pages}}">{{ pages }} </a></li>
                         {% endif %}
                             
                       
                             
                         {% endfor %}
                             
						


                        {% if page_obj.has_next   %}
                        <li><a href="?page={{page_obj.next_page_number }}">Next</a></li>
                            
                        {% else %}
                        <li class="disabled"></li>
                        {% endif %}
					</ul>
				</nav>
                    
                {% endif %}
                    

			</section>

		</main>

            
        {% endblock body %}
            
	